### ISSUE TITLE
add infernal and HMMer wrappers

### ISSUE THREAD

**Issue by RNAer** [biocore/micronota#7]
related to issue #6 

- [ ] infernal wrapper
- [ ] HMMER wrapper

**Comment by mortonjt** [comment]
I'll get started on the HMMER wrapper

**Comment by RNAer** [comment]
awesome!

**Comment by RNAer** [comment]
@mortonjt , have you got a chance to start working on it? it is probably good to issue pull request of your code as work in progress?

**Comment by mortonjt** [comment]
No I haven't gotten around to working on it.  Will push probably sometime
this weekend.

**Comment by mortonjt** [comment]
btw, it looks like infernal is already in [bfillings](https://github.com/biocore/burrito-fillings/blob/master/bfillings/infernal.py)

**Comment by RNAer** [comment]
needs lots of update. I am doing it.

**Comment by wasade** [comment]
@RNAer, would it make sense to also include ssu-align? It's based on Infernal but includes SSU specific models, or is there a better method at the moment for annotating SSU?

**Comment by RNAer** [comment]
RNAmmer? but it is a perl script and I am reluctant to use, although it is very highly cited. I plan to just use infernal to do that as it speeds up quite a lot in recent versions. obviously SSU-Align is more accurate, but SSU-Align is designed for aligning many SSU sequences, not for genome annotation. It assumes there's at most 1 SSU in each input sequence, which defeat the purpose.

**Comment by wasade** [comment]
I thought it would annotate all SSU in a sequence? I'm vaguely remembering
this now...

**Comment by RNAer** [comment]
nope. I got that from Eric.

**Comment by wasade** [comment]
Would it be possible to just use the models from SSU-Align?

**Comment by RNAer** [comment]
don't think so. I remember the CM model is the same (otherwise, the model in Rfam would be updated with it), but ssualign does something smart in aligning the seq.

**Comment by wasade** [comment]
oh, lame
