### ISSUE TITLE
Failed building wheel for scipy

### ISSUE THREAD

**Issue by sjanssen2** [biocore/micronota#73]
I am installing micronata on my Linux Mint laptop. Never used pyhton, conda or their dependencies before. After cloning the repo and changing into its directory a "pip install -e ." failes with the following message.
I guess it is because of a missing numpy installation.

(micronata)t440s x86_64 ~/Desktop/KnightLab/Micronata/repo_zech>pip install -e .
Obtaining file:///home/sjanssen/Desktop/KnightLab/Micronata/repo_zech
Collecting click>=6 (from micronota==0.1.0.dev0)
  Downloading click-6.6.tar.gz (283kB)
    100% |████████████████████████████████| 286kB 329kB/s 
Collecting scikit-bio>=0.4.0 (from micronota==0.1.0.dev0)
  Downloading scikit-bio-0.4.2.tar.gz (8.1MB)
    100% |████████████████████████████████| 8.1MB 121kB/s 
Collecting burrito>=0.9 (from micronota==0.1.0.dev0)
  Downloading burrito-0.9.1.tar.gz
Collecting bz2file>=0.98 (from scikit-bio>=0.4.0->micronota==0.1.0.dev0)
  Downloading bz2file-0.98.tar.gz
Collecting lockfile>=0.10.2 (from scikit-bio>=0.4.0->micronota==0.1.0.dev0)
  Downloading lockfile-0.12.2-py2.py3-none-any.whl
Collecting CacheControl>=0.11.5 (from scikit-bio>=0.4.0->micronota==0.1.0.dev0)
  Downloading CacheControl-0.11.6.tar.gz
Collecting contextlib2>=0.4.0 (from scikit-bio>=0.4.0->micronota==0.1.0.dev0)
  Downloading contextlib2-0.5.1.tar.gz
Collecting decorator>=3.4.2 (from scikit-bio>=0.4.0->micronota==0.1.0.dev0)
  Downloading decorator-4.0.9-py2.py3-none-any.whl
Collecting future>=0.14.3 (from scikit-bio>=0.4.0->micronota==0.1.0.dev0)
  Downloading future-0.15.2.tar.gz (1.6MB)
    100% |████████████████████████████████| 1.6MB 153kB/s 
Collecting IPython>=3.2.0 (from scikit-bio>=0.4.0->micronota==0.1.0.dev0)
  Downloading ipython-4.1.2-py3-none-any.whl (736kB)
    100% |████████████████████████████████| 737kB 272kB/s 
Collecting matplotlib>=1.4.3 (from scikit-bio>=0.4.0->micronota==0.1.0.dev0)
  Downloading matplotlib-1.5.1.tar.gz (54.0MB)
    100% |████████████████████████████████| 54.0MB 14kB/s 
Collecting natsort>=4.0.3 (from scikit-bio>=0.4.0->micronota==0.1.0.dev0)
  Downloading natsort-4.0.4-py2.py3-none-any.whl
Collecting numpy>=1.9.2 (from scikit-bio>=0.4.0->micronota==0.1.0.dev0)
  Downloading numpy-1.11.0.tar.gz (4.2MB)
    100% |████████████████████████████████| 4.2MB 114kB/s 
Collecting pandas>=0.17.0 (from scikit-bio>=0.4.0->micronota==0.1.0.dev0)
  Downloading pandas-0.18.0.tar.gz (7.1MB)
    100% |████████████████████████████████| 7.1MB 78kB/s 
Collecting scipy>=0.15.1 (from scikit-bio>=0.4.0->micronota==0.1.0.dev0)
  Downloading scipy-0.17.0.tar.gz (12.4MB)
    100% |████████████████████████████████| 12.4MB 30kB/s 
Collecting six>=1.9.0 (from scikit-bio>=0.4.0->micronota==0.1.0.dev0)
  Downloading six-1.10.0-py2.py3-none-any.whl
Collecting nose>=1.3.7 (from scikit-bio>=0.4.0->micronota==0.1.0.dev0)
  Downloading nose-1.3.7-py3-none-any.whl (154kB)
    100% |████████████████████████████████| 163kB 275kB/s 
Collecting requests (from CacheControl>=0.11.5->scikit-bio>=0.4.0->micronota==0.1.0.dev0)
  Downloading requests-2.9.1-py2.py3-none-any.whl (501kB)
    100% |████████████████████████████████| 501kB 107kB/s 
Collecting traitlets (from IPython>=3.2.0->scikit-bio>=0.4.0->micronota==0.1.0.dev0)
  Downloading traitlets-4.2.1-py2.py3-none-any.whl (67kB)
    100% |████████████████████████████████| 71kB 204kB/s 
Collecting simplegeneric>0.8 (from IPython>=3.2.0->scikit-bio>=0.4.0->micronota==0.1.0.dev0)
  Downloading simplegeneric-0.8.1.zip
Requirement already satisfied (use --upgrade to upgrade): setuptools>=18.5 in /home/sjanssen/anaconda3/envs/micronata/lib/python3.5/site-packages/setuptools-20.6.7-py3.5.egg (from IPython>=3.2.0->scikit-bio>=0.4.0->micronota==0.1.0.dev0)
Collecting pexpect (from IPython>=3.2.0->scikit-bio>=0.4.0->micronota==0.1.0.dev0)
  Downloading pexpect-4.0.1.tar.gz (143kB)
    100% |████████████████████████████████| 153kB 226kB/s 
Collecting pickleshare (from IPython>=3.2.0->scikit-bio>=0.4.0->micronota==0.1.0.dev0)
  Downloading pickleshare-0.7.2-py2.py3-none-any.whl
Collecting python-dateutil (from matplotlib>=1.4.3->scikit-bio>=0.4.0->micronota==0.1.0.dev0)
  Downloading python_dateutil-2.5.2-py2.py3-none-any.whl (201kB)
    100% |████████████████████████████████| 204kB 341kB/s 
Collecting pytz (from matplotlib>=1.4.3->scikit-bio>=0.4.0->micronota==0.1.0.dev0)
  Downloading pytz-2016.3-py2.py3-none-any.whl (479kB)
    100% |████████████████████████████████| 481kB 129kB/s 
Collecting cycler (from matplotlib>=1.4.3->scikit-bio>=0.4.0->micronota==0.1.0.dev0)
  Downloading cycler-0.10.0-py2.py3-none-any.whl
Collecting pyparsing!=2.0.0,!=2.0.4,>=1.5.6 (from matplotlib>=1.4.3->scikit-bio>=0.4.0->micronota==0.1.0.dev0)
  Downloading pyparsing-2.1.1-py2.py3-none-any.whl
Collecting ipython-genutils (from traitlets->IPython>=3.2.0->scikit-bio>=0.4.0->micronota==0.1.0.dev0)
  Downloading ipython_genutils-0.1.0-py2.py3-none-any.whl
Collecting ptyprocess>=0.5 (from pexpect->IPython>=3.2.0->scikit-bio>=0.4.0->micronota==0.1.0.dev0)
  Downloading ptyprocess-0.5.1-py2.py3-none-any.whl
Building wheels for collected packages: click, scikit-bio, burrito, bz2file, CacheControl, contextlib2, future, matplotlib, numpy, pandas, scipy, simplegeneric, pexpect
  Running setup.py bdist_wheel for click ... done
  Stored in directory: /home/sjanssen/.cache/pip/wheels/85/34/73/74fc76049d890d131db55346df1c8821b4d42468a993b2315e
  Running setup.py bdist_wheel for scikit-bio ... done
  Stored in directory: /home/sjanssen/.cache/pip/wheels/8b/cb/5f/0f473abc7ae5d5ff29891f9eba70902df141ea9b3c3777b042
  Running setup.py bdist_wheel for burrito ... done
  Stored in directory: /home/sjanssen/.cache/pip/wheels/04/6e/03/b773992d32f3761527a3f093f1857f86b27f83076f82084fa7
  Running setup.py bdist_wheel for bz2file ... done
  Stored in directory: /home/sjanssen/.cache/pip/wheels/e3/35/36/7906dd446f146d9bab436ddbf3f105022aec1bc25f9d1dc92b
  Running setup.py bdist_wheel for CacheControl ... done
  Stored in directory: /home/sjanssen/.cache/pip/wheels/62/be/ab/d70caecfd83e6135fbcace36cc763ed1fcd65097e4f41b1979
  Running setup.py bdist_wheel for contextlib2 ... done
  Stored in directory: /home/sjanssen/.cache/pip/wheels/69/10/11/32bef7b8857cbd724a51487711793db25d047d96cd7213c17e
  Running setup.py bdist_wheel for future ... done
  Stored in directory: /home/sjanssen/.cache/pip/wheels/d9/04/36/6bd807b5148e7c929d8f0991cc943a81f3287030a1b352e3fc
  Running setup.py bdist_wheel for matplotlib ... done
  Stored in directory: /home/sjanssen/.cache/pip/wheels/94/22/76/2f17479b2ff90623041a1ce6b6c2b88bcd68e4a24dd2456d9f
  Running setup.py bdist_wheel for numpy ... done
  Stored in directory: /home/sjanssen/.cache/pip/wheels/dc/c6/37/0a82876d354006c8bfec830bffcb455215968d8e3c22b9e155
  Running setup.py bdist_wheel for pandas ... done
  Stored in directory: /home/sjanssen/.cache/pip/wheels/18/40/72/afa14ca5e00158d0310726195311bb43c1ffd44dd6cbd581f0
  Running setup.py bdist_wheel for scipy ... error
  Complete output from command /home/sjanssen/anaconda3/envs/micronata/bin/python -u -c "import setuptools, tokenize;__file__='/tmp/pip-build-1i622p3t/scipy/setup.py';exec(compile(getattr(tokenize, 'open', open)(__file__).read().replace('\r\n', '\n'), __file__, 'exec'))" bdist_wheel -d /tmp/tmpymtg4iqrpip-wheel- --python-tag cp35:
  Traceback (most recent call last):
    File "<string>", line 1, in <module>
    File "/tmp/pip-build-1i622p3t/scipy/setup.py", line 265, in <module>
      setup_package()
    File "/tmp/pip-build-1i622p3t/scipy/setup.py", line 253, in setup_package
      from numpy.distutils.core import setup
  ImportError: No module named 'numpy'
  
  ----------------------------------------
  Failed building wheel for scipy
  Running setup.py clean for scipy
  Running setup.py bdist_wheel for simplegeneric ... done
  Stored in directory: /home/sjanssen/.cache/pip/wheels/51/3c/13/2b621669f3ba74b01380aefcc0af0f643bb42360e7248496ed
  Running setup.py bdist_wheel for pexpect ... done
  Stored in directory: /home/sjanssen/.cache/pip/wheels/ea/5b/53/4b65a279e1390ae81febe74f660ce01ef4655c9c1ec9acd9bf
Successfully built click scikit-bio burrito bz2file CacheControl contextlib2 future matplotlib numpy pandas simplegeneric pexpect
Failed to build scipy
Installing collected packages: click, bz2file, lockfile, requests, CacheControl, contextlib2, decorator, future, ipython-genutils, traitlets, simplegeneric, ptyprocess, pexpect, pickleshare, IPython, numpy, six, python-dateutil, pytz, cycler, pyparsing, matplotlib, natsort, pandas, scipy, nose, scikit-bio, burrito, micronota
  Running setup.py install for scipy ... done
  Running setup.py develop for micronota
Successfully installed CacheControl-0.11.6 IPython-4.1.2 burrito-0.9.1 bz2file-0.98 click-6.6 contextlib2-0.5.1 cycler-0.10.0 decorator-4.0.9 future-0.15.2 ipython-genutils-0.1.0 lockfile-0.12.2 matplotlib-1.5.1 micronota natsort-4.0.4 nose-1.3.7 numpy-1.11.0 pandas-0.18.0 pexpect-4.0.1 pickleshare-0.7.2 ptyprocess-0.5.1 pyparsing-2.1.1 python-dateutil-2.5.2 pytz-2016.3 requests-2.9.1 scikit-bio-0.4.2 scipy-0.17.0 simplegeneric-0.8.1 six-1.10.0 traitlets-4.2.1

**Comment by RNAer** [comment]
hmm, try these cmd:
conda config --add channels https://conda.anaconda.org/zechxu
conda install --file ci/conda_requirements.txt
pip install -r ci/pip_requirements.txt

then you should be all set to go.

**Comment by sjanssen2** [comment]
You are right. It works for me. Thanks!
